In [103]:
# load libraries
import pandas as pd
import numpy as np
from pycaret.regression import *

df = pd.read_excel('DS - Assignment Part 1 data set.xlsx')
#remane columns
df.rename(columns={'Distance from nearest Metro station (km)':'nearest Metro(km)','House price of unit area': 'Price'}, inplace=True)

In [104]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 414 entries, 0 to 413
Data columns (total 9 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Transaction date              414 non-null    float64
 1   House Age                     414 non-null    float64
 2   nearest Metro(km)             414 non-null    float64
 3   Number of convenience stores  414 non-null    int64
 4   latitude                      414 non-null    float64
 5   longitude                     414 non-null    float64
 6   Number of bedrooms            414 non-null    int64
 7   House size (sqft)             414 non-null    int64
 8   Price                         414 non-null    float64
dtypes: float64(6), int64(3)
memory usage: 29.2 KB

In [105]:
df.drop('Transaction date', axis=1, inplace=True)

In [118]:
# pycaret for regression
from pycaret.regression import *
reg = setup(data = df, target = 'Price', normalize=False, 
transformation= False, ignore_low_variance=True, remove_outliers=False)

Setup Succesfully Completed.

In [113]:
gbr = create_model('rf')

In [114]:
tune_model(gbr)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=40, max_features='sqrt', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=2,
                      min_samples_split=7, min_weight_fraction_leaf=0.0,
                      n_estimators=280, n_jobs=-1, oob_score=False,
                      random_state=3246, verbose=0, warm_start=False)

In [119]:
best_model = compare_models()

In [116]:
xgb = create_model('xgboost')

In [117]:
tuned_xgb = tune_model(xgb)